
#include "jstudio.h"
#include "romassets.h"

#define BACKGROUND 0
#define P2_CURSOR 1
#define P1_CURSOR 2
#define P1_FIGHTER 3
#define P2_FIGHTER 4

#define P1_HB_BODY 49
#define P1_HB_DUCK P1_HB_BODY + 1
#define P1_HB_ATTACK P1_HB_DUCK + 1
#define P2_HB_BODY P1_HB_ATTACK + 1
#define P2_HB_DUCK P2_HB_BODY + 1
#define P2_HB_ATTACK P2_HB_DUCK + 1

//-----------------------------------------------------------------------------------------------------
#define CAGE 1
#define KANO 2
#define RAIDEN 3
#define KANG 4
#define SCORPION 5
#define SUBZERO 6
#define SONYA 7
#define REPTILE 8
#define KASUMI 9

//-----------------------------------------------------------------------------------------------------
#define SOUND_CHANNEL_PLAYER1 1
#define SOUND_CHANNEL_PLAYER2 2
#define SOUND_CHANNEL_ANNOUNCER 3
#define SOUND_CHANNEL_MISC 4

//-----------------------------------------------------------------------------------------------------
#define SCORPION_IDLE_FRAME_COUNT 7
#define SCORPION_WALK_FRAME_COUNT 9

#define KANO_IDLE_FRAME_COUNT 7
#define KANO_WALK_FRAME_COUNT 9
#define KANO_JUMP_FRAME_COUNT 4
#define KANO_JUMP_ROLL_FRAME_COUNT 7
#define KANO_DUCK_FRAME_COUNT 3
#define KANO_BLOCK_FRAME_COUNT 3
#define KANO_BLOCK_HIT_FRAME_COUNT 6
#define KANO_BLOCK_DUCK_FRAME_COUNT 2
#define KANO_BLOCK_DUCK_HIT_FRAME_COUNT 6
#define KANO_LOW_PUNCH_FRAME_COUNT 5
#define KANO_HIGH_PUNCH_FRAME_COUNT 5
#define KANO_LOW_KICK_FRAME_COUNT 7
#define KANO_HIGH_KICK_FRAME_COUNT 7
#define KANO_JUMP_PUNCH_FRAME_COUNT 3
#define KANO_JUMP_KICK_FRAME_COUNT 3
#define KANO_UPPERCUT_FRAME_COUNT 6
#define KANO_KIPUP_FRAME_COUNT 5
#define KANO_SWEEP_FRAME_COUNT 9

#define KANO_HIT_BACK_FRAME_COUNT 5
#define KANO_HIT_LOW_FRAME_COUNT 4
#define KANO_HIT_HIGH_FRAME_COUNT 4
#define KANO_HIT_FALL_FRAME_COUNT 6
#define KANO_HIT_SWEEP_FRAME_COUNT 6

#define CAGE_IDLE_FRAME_COUNT 7
#define CAGE_WALK_FRAME_COUNT 9
#define CAGE_JUMP_FRAME_COUNT 4
#define CAGE_JUMP_ROLL_FRAME_COUNT 7
#define CAGE_DUCK_FRAME_COUNT 3
#define CAGE_BLOCK_FRAME_COUNT 3
#define CAGE_BLOCK_HIT_FRAME_COUNT 6
#define CAGE_BLOCK_DUCK_FRAME_COUNT 2
#define CAGE_BLOCK_DUCK_HIT_FRAME_COUNT 6
#define CAGE_LOW_PUNCH_FRAME_COUNT 5
#define CAGE_HIGH_PUNCH_FRAME_COUNT 5
#define CAGE_LOW_KICK_FRAME_COUNT 5
#define CAGE_HIGH_KICK_FRAME_COUNT 7
#define CAGE_JUMP_PUNCH_FRAME_COUNT 3
#define CAGE_JUMP_KICK_FRAME_COUNT 3
#define CAGE_UPPERCUT_FRAME_COUNT 6
#define CAGE_KIPUP_FRAME_COUNT 5
#define CAGE_SWEEP_FRAME_COUNT 9

#define CAGE_HIT_LOW_FRAME_COUNT 4
#define CAGE_HIT_HIGH_FRAME_COUNT 4
#define CAGE_HIT_BACK_FRAME_COUNT 6
#define CAGE_HIT_FALL_FRAME_COUNT 6
#define CAGE_HIT_SWEEP_FRAME_COUNT 6

#define KANG_IDLE_FRAME_COUNT 7
#define KANG_WALK_FRAME_COUNT 9
#define KANG_JUMP_FRAME_COUNT 4
#define KANG_JUMP_ROLL_FRAME_COUNT 7
#define KANG_DUCK_FRAME_COUNT 3
#define KANG_BLOCK_FRAME_COUNT 3
#define KANG_BLOCK_HIT_FRAME_COUNT 6
#define KANG_BLOCK_DUCK_FRAME_COUNT 2
#define KANG_BLOCK_DUCK_HIT_FRAME_COUNT 6
#define KANG_LOW_PUNCH_FRAME_COUNT 5
#define KANG_HIGH_PUNCH_FRAME_COUNT 5
#define KANG_LOW_KICK_FRAME_COUNT 5
#define KANG_HIGH_KICK_FRAME_COUNT 7
#define KANG_JUMP_PUNCH_FRAME_COUNT 3
#define KANG_JUMP_KICK_FRAME_COUNT 3
#define KANG_UPPERCUT_FRAME_COUNT 6
#define KANG_KIPUP_FRAME_COUNT 5
#define KANG_SWEEP_FRAME_COUNT 9

#define KANG_HIT_LOW_FRAME_COUNT 4
#define KANG_HIT_HIGH_FRAME_COUNT 4
#define KANG_HIT_BACK_FRAME_COUNT 5
#define KANG_HIT_FALL_FRAME_COUNT 6
#define KANG_HIT_SWEEP_FRAME_COUNT 6

#define RAIDEN_IDLE_FRAME_COUNT 10
#define RAIDEN_WALK_FRAME_COUNT 9
#define RAIDEN_JUMP_FRAME_COUNT 4
#define RAIDEN_JUMP_ROLL_FRAME_COUNT 7
#define RAIDEN_DUCK_FRAME_COUNT 3
#define RAIDEN_BLOCK_FRAME_COUNT 3
#define RAIDEN_BLOCK_HIT_FRAME_COUNT 6
#define RAIDEN_BLOCK_DUCK_FRAME_COUNT 2
#define RAIDEN_BLOCK_DUCK_HIT_FRAME_COUNT 6
#define RAIDEN_LOW_PUNCH_FRAME_COUNT 5
#define RAIDEN_HIGH_PUNCH_FRAME_COUNT 5
#define RAIDEN_LOW_KICK_FRAME_COUNT 7
#define RAIDEN_HIGH_KICK_FRAME_COUNT 7
#define RAIDEN_JUMP_PUNCH_FRAME_COUNT 3
#define RAIDEN_JUMP_KICK_FRAME_COUNT 3
#define RAIDEN_UPPERCUT_FRAME_COUNT 6
#define RAIDEN_KIPUP_FRAME_COUNT 5
#define RAIDEN_SWEEP_FRAME_COUNT 9

#define RAIDEN_HIT_LOW_FRAME_COUNT 4
#define RAIDEN_HIT_HIGH_FRAME_COUNT 4
#define RAIDEN_HIT_BACK_FRAME_COUNT 5
#define RAIDEN_HIT_FALL_FRAME_COUNT 6
#define RAIDEN_HIT_SWEEP_FRAME_COUNT 6

#define SUBZERO_IDLE_FRAME_COUNT 12
#define SUBZERO_WALK_FRAME_COUNT 9
#define SUBZERO_JUMP_FRAME_COUNT 4
#define SUBZERO_JUMP_ROLL_FRAME_COUNT 7
#define SUBZERO_DUCK_FRAME_COUNT 3
#define SUBZERO_BLOCK_FRAME_COUNT 3
#define SUBZERO_BLOCK_HIT_FRAME_COUNT 6
#define SUBZERO_BLOCK_DUCK_FRAME_COUNT 2
#define SUBZERO_BLOCK_DUCK_HIT_FRAME_COUNT 6
#define SUBZERO_LOW_PUNCH_FRAME_COUNT 5
#define SUBZERO_HIGH_PUNCH_FRAME_COUNT 5
#define SUBZERO_LOW_KICK_FRAME_COUNT 5
#define SUBZERO_HIGH_KICK_FRAME_COUNT 7
#define SUBZERO_JUMP_PUNCH_FRAME_COUNT 3
#define SUBZERO_JUMP_KICK_FRAME_COUNT 3
#define SUBZERO_UPPERCUT_FRAME_COUNT 6
#define SUBZERO_KIPUP_FRAME_COUNT 5
#define SUBZERO_SWEEP_FRAME_COUNT 9

#define SUBZERO_HIT_LOW_FRAME_COUNT 4
#define SUBZERO_HIT_HIGH_FRAME_COUNT 4
#define SUBZERO_HIT_BACK_FRAME_COUNT 5
#define SUBZERO_HIT_FALL_FRAME_COUNT 6
#define SUBZERO_HIT_SWEEP_FRAME_COUNT 6

#define SONYA_IDLE_FRAME_COUNT 7
#define SONYA_WALK_FRAME_COUNT 7
#define SONYA_JUMP_FRAME_COUNT 4
#define SONYA_JUMP_ROLL_FRAME_COUNT 7
#define SONYA_DUCK_FRAME_COUNT 2
#define SONYA_BLOCK_FRAME_COUNT 3
#define SONYA_BLOCK_HIT_FRAME_COUNT 6
#define SONYA_BLOCK_DUCK_FRAME_COUNT 2
#define SONYA_BLOCK_DUCK_HIT_FRAME_COUNT 6
#define SONYA_LOW_PUNCH_FRAME_COUNT 5
#define SONYA_HIGH_PUNCH_FRAME_COUNT 5
#define SONYA_LOW_KICK_FRAME_COUNT 7
#define SONYA_HIGH_KICK_FRAME_COUNT 7
#define SONYA_JUMP_PUNCH_FRAME_COUNT 3
#define SONYA_JUMP_KICK_FRAME_COUNT 3
#define SONYA_UPPERCUT_FRAME_COUNT 6
#define SONYA_KIPUP_FRAME_COUNT 5
#define SONYA_SWEEP_FRAME_COUNT 7

#define SONYA_HIT_LOW_FRAME_COUNT 4
#define SONYA_HIT_HIGH_FRAME_COUNT 4
#define SONYA_HIT_BACK_FRAME_COUNT 5
#define SONYA_HIT_FALL_FRAME_COUNT 6
#define SONYA_HIT_SWEEP_FRAME_COUNT 6

#define TOTAL_BLOOD_COUNT 10
#define TOTAL_BLOOD_SQUIRT_COUNT 6