struct SoundHandler {
    bool EnableSFX;
    bool EnableMusic;
    short VolumeSFX;
    short VolumeMusic;
    bool UsePrimaryChannel;
};

void sfxFight(struct SoundHandler* soundHandler);
void sfxJohnnyCage(struct SoundHandler* soundHandler);
void sfxKano(struct SoundHandler* soundHandler);
void sfxRaiden(struct SoundHandler* soundHandler);
void sfxLiuKang(struct SoundHandler* soundHandler);
void sfxScorpion(struct SoundHandler* soundHandler);
void sfxSubzero(struct SoundHandler* soundHandler);
void sfxSonya(struct SoundHandler* soundHandler);
void sfxKasumi(struct SoundHandler* soundHandler);
void sfxP1Cursor(struct SoundHandler* soundHandler);
void sfxP2Cursor(struct SoundHandler* soundHandler);
void sfxGong(struct SoundHandler* soundHandler);
void sfxIntro(struct SoundHandler* soundHandler);
void sfxHiyaMale(struct SoundHandler* soundHandler);
void sfxHiyaFemale(struct SoundHandler* soundHandler);
void sfxHiyaKang(struct SoundHandler* soundHandler);
void sfxHiyaNinja(struct SoundHandler* soundHandler);
void sfxBlock(struct SoundHandler* soundHandler);
void sfxGroanMale(struct SoundHandler* soundHandler);
void sfxGroanFemale(struct SoundHandler* soundHandler);
void sfxYellMale(struct SoundHandler* soundHandler);
void sfxYellFemale(struct SoundHandler* soundHandler);
void sfxYellKang(struct SoundHandler* soundHandler);
void sfxJumpMale(struct SoundHandler* soundHandler);
void sfxJumpFemale(struct SoundHandler* soundHandler);
void sfxJumpNinja(struct SoundHandler* soundHandler);
void sfxThrowMale(struct SoundHandler* soundHandler);
void sfxThrowFemale(struct SoundHandler* soundHandler);
void sfxThrowNinja(struct SoundHandler* soundHandler);
void sfxJumpRoll(struct SoundHandler* soundHandler);
void sfxCageYeah(struct SoundHandler* soundHandler);
void sfxCageGreenbolt(struct SoundHandler* soundHandler);
void sfxKanoYell(struct SoundHandler* soundHandler);
void sfxKanoKnife(struct SoundHandler* soundHandler);
void sfxKanoCannonBallStart(struct SoundHandler* soundHandler);
void sfxKanoCannonBall(struct SoundHandler* soundHandler);
void sfxSonyaRings(struct SoundHandler* soundHandler);
void sfxSubzeroFreeze(struct SoundHandler* soundHandler);
void sfxSubzeroFreezeEnd(struct SoundHandler* soundHandler);
void sfxSubzeroSlide(struct SoundHandler* soundHandler);
void sfxScorpionHarpoon(struct SoundHandler* soundHandler);
void sfxScorpionTeleport(struct SoundHandler* soundHandler);
void sfxScorpionGetOverHere(struct SoundHandler* soundHandler);
void sfxRaidenLightning(struct SoundHandler* soundHandler);
void sfxRaidenLightningEnd(struct SoundHandler* soundHandler);
void sfxRaidenTeleport(struct SoundHandler* soundHandler);
void sfxRaidenTorpedo(struct SoundHandler* soundHandler);
void sfxRaidenIdleZap(struct SoundHandler* soundHandler);
void sfxKangFlyingKick(struct SoundHandler* soundHandler);
void sfxKanoHeadbutt(struct SoundHandler* soundHandler);
void sfxHit(struct SoundHandler* soundHandler);
void sfxImpact(struct SoundHandler* soundHandler);
void sfxBlood(struct SoundHandler* soundHandler);
void sfxSwing(struct SoundHandler* soundHandler);
void sfxThud(struct SoundHandler* soundHandler);
void sfxTruFun(struct SoundHandler* soundHandler);
void sfxTitleRise(struct SoundHandler* soundHandler);
void sfxTitleThud(struct SoundHandler* soundHandler);
void sfxTitleStart(struct SoundHandler* soundHandler);
void sfxCrowdAww(struct SoundHandler* soundHandler);
void sfxCrowdClap(struct SoundHandler* soundHandler);
void sfxAnnouncerExcellent(struct SoundHandler* soundHandler);
void sfxAnnouncerLaugh(struct SoundHandler* soundHandler);
void sfxFinishHer(struct SoundHandler* soundHandler);
void sfxFinishHim(struct SoundHandler* soundHandler);
void sfxWins(struct SoundHandler* soundHandler);
void sfxFlawless(struct SoundHandler* soundHandler);
void sfxFatality(struct SoundHandler* soundHandler);
void musicTitle(struct SoundHandler* soundHandler);
void musicStageGates(struct SoundHandler* soundHandler);
void musicStagePit(struct SoundHandler* soundHandler);
void musicStageWarrior(struct SoundHandler* soundHandler);
void musicStageGoro(struct SoundHandler* soundHandler);
void musicStageThrone(struct SoundHandler* soundHandler);
void musicStop();
void soundNextChannel(struct SoundHandler* soundHandler);
short soundGetChannel(struct SoundHandler* soundHandler);