int stageGet();
void stageInit();
void stageSetNext();
void stageLoadVsBattle();
void stageUpdate();
int stageGetFighterHitboxIndex();
int stageGetHeight();
int stageGetStartX();
int stageGetStartY();
void stageMove(int direction, int offset);
void stageHideShowSprite(int spriteIndex, int width);
void stageResetTicks();
void stagePositionAssets();
int stageGetFatalityPalette();