int stageGet();
void stageInit();
void stageSetNext();
void stageLoadVsBattle();
void stageUpdate();
int stageGetFighterHitboxIndex();
int stageGetHeight();
int stageGetStartX();
void stageMove(int direction);
void stageHideShowSprite(int spriteIndex, int width);
void stageResetTicks();